const domainFeatures = {
  SPARK_BRONZE_YEARLY: [
    { label: "Domain Lander" },
    { label: "Basic Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
  ],
  SPARK_SILVER_YEARLY: [
    { label: "Domain Lander" },
    { label: "Basic Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
  ],
  SPARK_GOLD_MONTHLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "Custom Links" },
    { label: "BrandForm ", note: "brandform" },
    { label: "BrandShare ", note: "brandshare" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    {
      label: "BrandGear (2 Items on Your World Life) ",
      note: "brandgear",
    },
    { label: "BrandMail (Q4 2026)" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
  SPARK_GOLD_YEARLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "Custom Links" },
    { label: "BrandForm ", note: "brandform" },
    { label: "BrandShare ", note: "brandshare" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    {
      label: "BrandGear (2 Items on Your World Life) ",
      note: "brandgear",
    },
    { label: "BrandMail (Q4 2026)" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
  PULSE_BRONZE_YEARLY: [
    { label: "Domain Lander" },
    { label: "Basic Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
  ],
  PULSE_SILVER_MONTHLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    { label: "BrandBook (Booking Calendar)" },
    { label: "QR Code Generator" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
  PULSE_SILVER_YEARLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    { label: "BrandBook (Booking Calendar)" },
    { label: "QR Code Generator" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
  PULSE_GOLD_MONTHLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "Custom Link" },
    { label: "Dedicated Support" },
    { label: "BrandForm ", note: "brandform" },
    { label: "BrandShare ", note: "brandshare" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    { label: "BrandBook (Booking Calendar)" },
    { label: "QR Code Generator" },
    { label: "Echo (Realtime Requests)" },
    { label: "BrandGear ", note: "brandgear" },
    { label: "Dedicated merchandise collection" },
    { label: "VCF Creator" },
    { label: "ZIP uploader" },
    { label: "Analytics dashboard (Q1 2026)" },
    { label: "PulseTrack (Link Tracking)" },
    { label: "BrandTrack" },
    { label: "BrandMail (Q4 2026)" },
    { label: "Access to form data (Q4 2026)" },
    { label: "Access to request data (Q4 2026)" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
  PULSE_GOLD_YEARLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "Custom Link" },
    { label: "Dedicated Support" },
    { label: "BrandForm ", note: "brandform" },
    { label: "BrandShare ", note: "brandshare" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    { label: "BrandBook (Booking Calendar)" },
    { label: "QR Code Generator" },
    { label: "Echo (Realtime Requests)" },
    { label: "BrandGear ", note: "brandgear" },
    { label: "Dedicated merchandise collection" },
    { label: "VCF Creator" },
    { label: "ZIP uploader" },
    { label: "Analytics dashboard" },
    { label: "PulseTrack (Link Tracking)" },
    { label: "BrandTrack" },
    { label: "BrandMail (Q4 2026)" },
    { label: "Access to form data (Q4 2026)" },
    { label: "Access to request data (Q4 2026)" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
  POWER_SILVER_YEARLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "Custom Link" },
    { label: "BrandForm ", note: "brandform" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    { label: "BrandBook (Booking Calendar)" },
    { label: "QR Code Generator" },
    { label: "VCF Creator" },
    { label: "ZIP uploader" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
  POWER_GOLD_MONTHLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "Custom Link" },
    { label: "Dedicated Support" },
    { label: "BrandForm ", note: "brandform" },
    { label: "BrandShare ", note: "brandshare" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    { label: "BrandBook (Booking Calendar)" },
    { label: "QR Code Generator" },
    { label: "Echo (Live Requests)" },
    { label: "BrandGear - 8 items on YWL", note: "brandgear" },
    { label: "Dedicated Merchandise Collection" },
    { label: "VCF Creator" },
    { label: "ZIP uploader" },
    { label: "Analytics dashboard" },
    { label: "PulseTrack (Link Tracking)" },
    { label: "BrandTrack" },
    { label: "BrandMail (Q4 2026)" },
    { label: "Access to form data (Q4 2026)" },
    { label: "Access to request data (Q4 2026)" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
  POWER_GOLD_YEARLY: [
    { label: "Domain Lander" },
    { label: "Personal Look and Feel" },
    { label: "Social media links (links only)" },
    { label: "Mobile responsive design" },
    { label: "BrandDesk" },
    { label: "Custom Link" },
    { label: "Dedicated Support" },
    { label: "BrandForm ", note: "brandform" },
    { label: "BrandShare ", note: "brandshare" },
    { label: "SPIN" },
    { label: "BrandTap (Black NFC Wristband)" },
    { label: "BrandBook (Booking Calendar)" },
    { label: "QR Code Generator" },
    { label: "Echo (Live Requests)" },
    { label: "BrandGear - 8 items on YWL", note: "brandgear" },
    { label: "Dedicated Merchandise Collection" },
    { label: "VCF Creator" },
    { label: "ZIP uploader" },
    { label: "Analytics dashboard" },
    { label: "PulseTrack (Link Tracking)" },
    { label: "BrandTrack" },
    { label: "BrandMail (Q4 2026)" },
    { label: "Access to form data (Q4 2026)" },
    { label: "Access to request data (Q4 2026)" },
    { label: "Add-On Apps (Q4 2026)" },
  ],
};

export default domainFeatures;
