export const colors = [
  { label: "Logo Click", color: "#4FBC8F" },
  { label: "Info Submission", color: "#E59927" },
  { label: "Download Info", color: "#233366" },
  { label: "View Merchandise", color: "#5A7EDF" },
  { label: "View Live Board", color: "#CCEF87" },
  { label: "Check Terms & Conditions", color: "#95BF4D" },
  { label: "Check Privacy Policy", color: "#D43825" },
  { label: "Apply Discount Code", color: "#E38026" },
  { label: "Create Branbook Booking", color: "#95BF4D" },
  { label: "Create Echo Request", color: "#A53428" },
  { label: "Select booking slot", color: "#C9DD34" },
  { label: "Open Echo Request", color: "#85C237" },
  { label: "View FACEBOOK", color: "#1877F2" },
  { label: "View TWITTER", color: "#1DA1F2" },
  { label: "View LINKEDIN", color: "#0A66C2" },
  { label: "View YOUTUBE", color: "#FF0000" },
  { label: "View TIKTOK", color: "#010101" },
  { label: "View INSTAGRAM", color: "#E1306C" },
  { label: "View SNAPCHAT", color: "#FFFC00" },
  { label: "View REDDIT", color: "#FF4500" },
  { label: "View TUMBLR", color: "#36465D" },
  { label: "View PINTEREST", color: "#E60023" },
  { label: "View TELEGRAM", color: "#0088CC" },
  { label: "View EMAIL", color: "#D44638" },
  { label: "View WECHAT", color: "#7BB32E" },
  { label: "View PHONE", color: "#6C6C6C" },
  { label: "View WHATSAPP", color: "#25D366" },
  { label: "View DISCORD", color: "#5865F2" },
  { label: "View TWITCH", color: "#9146FF" },
  { label: "View GITHUB", color: "#181717" },
  { label: "View SOUNDCLOUD", color: "#FF5500" },
  { label: "View VIMEO", color: "#1AB7EA" },
  { label: "View SPOTIFY", color: "#1DB954" },
  { label: "View CLUBHOUSE", color: "#000000" },
  { label: "View PERISCOPE", color: "#40B0DF" },
  { label: "View DRIBBLE", color: "#EA4C89" },
  { label: "View BEHANCE", color: "#1769FF" },
  { label: "View DAILYMOTION", color: "#0066DC" },
  { label: "View MIXCLOUD", color: "#FF8800" },
  { label: "View FLICKR", color: "#FF0084" },
  { label: "View ANCHOR", color: "#4951EC" },
  { label: "View PATREON", color: "#F96854" },
  { label: "View NEXTDOOR", color: "#00A67E" },
  { label: "View CUSTOM", color: "#4FBC8F" },
];
