export const response = {
  HOME_ROUTE_MESSAGE: "Home route",
  UNAUTHORIZE_ERROR_MESSAGE: "Unauthorize user!",
  ROUTE_NOT_FOUND_MESSAGE: "Route not found!",
  USER_ALREADY_EXIST_MESSAGE: "Email already exist!",
  REGISTRATION_SUCCESS_MESSAGE: "Successful, redirect to payment",
  EMAIL_VERIFICATION_CODE_RESPONSE: "Verify Your Email for My Brand Life",
  NAME_RESPONSE: "The My Brand Life Team",
  OUTRO_RESPONSE: "©2025 MyBrandLife.me. All rights reserved.",
  USE_VERIFICATION_CODE_TO_VERIFY_EMAIL_RESPONSE:
    "Welcome to My Brand Life! Please use the following confirmation code to verify your email address.",
  SINGNATURE_RESPONSE: "Kind regards",
  IGNORE_EMAIL_RESPONSE:
    "If you have not signed up for this account, you can ignore this email.",
  DATA_NOT_FOUND_MESSAGE: "Data not found!",
  DELETE_SUCCESS_MESSAGE: "Delete successful",
  PASSWORD_NOT_MATCH_MESSAGE: "Password incorrect!",
  LOGIN_SUCCESS_MESSAGE: "Login successful",
  QUERY_SUCCESSFUL_MESSAGE: "Query successful",
  UPDATE_SUCCESSFUL_MESSAGE: "Update successful",
  ONBOARDING_SUCCESSFUL_MESSAGE: "Onboard submit successful",
  INCORRECT_REFERRAL_CODE_MESSAGE: "Incorrect referral code!",
  BRANDSHARE_CODE_ALREADY_EXIST: "BrandShare code already exist!",
  VALID_REFERRAL_CODE_MESSAGE: "Referral code Valid",
  TOKEN_EXPIRED_MESSAGE: "This code expired. Request a new one.",
  VERIFY_SUCCESSFUL_MESSAGE: "Email verified! Redirecting…",
  OTP_INCORRECT_MESSAGE: "OTP incorrect, Try again!",
  USER_UNVERIFYED_MESSAGE: "User not activated!",
  OTP_CODE_SEND_MESSAGE: "OTP code send",
  MESSAGE_SEND_SUCCESSFUL_MESSAGE: "Message send successful",
  REQUEST_SUBMIT_SUCCESSFUL_MESSAGE: "Request submit successful",
  LANDER_ALREADY_EXIST_MESSAGE: "Landername alreadt exist!",
  INVALID_TOKEN_MESSAGE: "Invalid token",
  LOGOUT_SUCCESSFUL_MESSAGE: "Logut Successful",
  ONBOARD_ALREADY_CREATED_MESSAGE: "Onboard already created!",
  INVALID_PLAN_MESSAGE: "Invalid plan!",
  REFFERAL_ALREADY_EXIST: "Referral code already exist!",
  CORS_ERROR_MESSAGE: "Cors error origin not allow!",
  INVALID_SECURE_KEY_MESSAGE: "Invalid secure Key!",
  USER_VERIFY_SUCCESSFUL_MESSAGE: "Verify successful",
  FORM_SUBMITION_SUCCESSFUL_MESSAGE: "Submit successful, redireting",
  BOOKING_SUBMIT_SUCCESSFUL: "Booking submit successful",
  ACCOUNT_IS_DEACTIVATE_MESSAGE: "Deactivate account successful",
  CONNECTION_REDIRECT_MESSAGE: "Connection redirect",
  USER_STRIPE_CONNECTION_FAILED: "Stripe connection failed!",
  RESET_LINK_SEND_SUCCESSFUL: "Reset password link sent to your email.",
  TOKEN_INVALID_MESSAGE: "Token invalid!",
  PARTNER_CREATE_SUCCESSFUL_MESSAGE: "Partner create successful",
  FORM_SUBMIT_SUCCESSFUL: "Form submit successful",
  REFERRAL_CODE_CREATE_SUCCESSFUL: "Referral code create successful",
  REFERRAL_CODE_EXPIRED: "Referral code expired!",
  REPORT_SUBMIT_SUCCESSFUL_MESSAGE: "Report submit successful",
  ONBOARD_DOES_NOT_EXIST: "Onboard does not exist!",
  ORDER_NOT_FOUND_MESSAGE: "Order not found!",
  LANDERNAME_ALREADY_EXIST: "Lander not available!",
  LANDERNAME_AVAILABLE_MESSAGE: "Lander available",
  ERROR_MESSAGE: "Something went wrong!",
  SOCKET_IO_ERROR_MESSAGE: "Socket.io not initialized.",
  GOOGLE_CALENDAR_NOT_CONNECTED: "Google calendar not connected",
  USER_ID_MISSING_IN_SUBSCRIPTION: "User ID missing in subscription metadata",
  CUSTOMER_HAS_BEEN_DELETED: "Customer has been deleted",
  CUSTOMER_ID_MISSING_ON_INVOICE: "Customer ID missing on invoice",
  NO_RECIPENT_EMAIL_PROVIDED: "No recipient emails provided",
  INVALID_USER_MESSAGE: "Ivalid user!",
  PULSETRACK_CREATE_SUCCESSFUL: "Pulsetrack create successful",
  PULSETRACK_ID_INVALID_MESSAGE: "Pulsetrack id invalid!",
  PULSETRACK_ID_VALID_MESSAGE: "Pulsetrack id is valid",
  PULSETRACK_ID_IS_NOT_EDITABLE: "Pulsetrack ID is not editable",
  WRISTBAND_ADDED_SUCCESSFUL: "Wristband added successful",
  USER_ASSIGNED_SUCCESSFUL: "User assigned successful",
  WRISTBAND_CREATE_SUCCESSFUL: "Wristband create successful",
  INVALID_EXPORT_FILE_TYPE: "Invalid type. Allowed: csv or pdf",
  SPIN_UPDATE_SUCCESSFUL: "Spin update successful",
  SPIN_GROUP_CREATE_SUCCESSFUL: "Spin create successful",
  DUPLICAT_GROUP_MESSAGE: "Duplicate group error",
};

export default response;
